### ISSUE TITLE
Fail to load tutorial-part01.lisp

### ISSUE THREAD

**Issue by maacl** [podiki/cl-tcod-tutorial#2]
I get the following error when trying to load ```tutorial-part01.lisp```:

```
The assertion (PROBE-FILE TCOD::FONTFILE) failed with
TCOD::FONTFILE = "arial10x10.png".
   [Condition of type SIMPLE-ERROR]
```
The font file is in the dir, so I suspect that this is some kind of emacs/path issue, but I don't know how to resolve it.

**Comment by podiki** [comment]
Because you mention emacs, I'm guessing you are running with SLIME. Your error is probably because SLIME's working directory is not the same as where you have `tutorial-part01.lisp`. By default SLIME should use the directory of the working buffer when you invoke it. So if you open the lisp file first and then start SLIME, it will use that directory. You can change the working directory in a running SLIME by typing a `,` and then `cd` in the SLIME buffer; see [the REPL documentation](https://common-lisp.net/project/slime/doc/html/Shortcuts.html#Shortcuts).

Did that do it?

**Comment by maacl** [comment]
Yeah, that did the trick, thanks.
